FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Vl.Challenge.API/Vl.Challenge.API.csproj", "Vl.Challenge.API/"]
RUN dotnet restore "Vl.Challenge.API/Vl.Challenge.API.csproj"
COPY . .
WORKDIR "/src/Vl.Challenge.API"
RUN dotnet build "Vl.Challenge.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Vl.Challenge.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Vl.Challenge.API.dll"]